version: "3.9"

services:
    
    admin_frontend:
        image: docker/admin_frontend
        container_name: admin_frontend
        build:
            context: ./frontend
        ports:
          - "6000:6000"
        networks:
          - mynetwork
          - jenkins
    admin_backend:
        image: docker/admin_backend
        container_name: admin_backend
        env_file:
            - ./backend/.production.env
        volumes:
          - ./static:/usr/node/app/public
        build:
            context: ./backend
        networks:
          - mynetwork
          - jenkinstwork
networks:
  mynetwork:
    external:
      name: delivglobalnetwork           
  jenkinstwork:
      external:
        name: jenkins
            